import catalog from "@/data/catalog.json";
import type { CatalogFood } from "./foods";

/**
 * Generic foods (fruit, vegetables, cuts of meat, pasta…) that have no
 * barcode to scan. Values are from USDA FoodData Central; the list is
 * generated by scripts/catalog/build.mjs, never edited by hand. Picking one
 * copies it into the user's own foods.
 */
export const CATALOG = catalog as CatalogFood[];
